"""rename metadata to meta_data in data_points

Revision ID: 662035ea71a4
Revises: 564a2e17e876
Create Date: 2025-10-12 16:01:19.061760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '662035ea71a4'
down_revision: Union[str, None] = '564a2e17e876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_points', sa.Column('task_id', sa.Integer(), nullable=False))
    op.add_column('data_points', sa.Column('data_type', sa.String(length=50), nullable=False))
    op.add_column('data_points', sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('data_points', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('data_points', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_data_points_task_id'), 'data_points', ['task_id'], unique=False)
    op.create_index(op.f('ix_data_points_timestamp'), 'data_points', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'data_points', 'tasks', ['task_id'], ['id'])
    op.drop_column('data_points', 'value')
    op.drop_column('data_points', 'source')
    op.drop_column('data_points', 'name')
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'user_id')
    op.add_column('data_points', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('data_points', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('data_points', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'data_points', type_='foreignkey')
    op.drop_index(op.f('ix_data_points_timestamp'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_task_id'), table_name='data_points')
    op.drop_column('data_points', 'timestamp')
    op.drop_column('data_points', 'meta_data')
    op.drop_column('data_points', 'value_json')
    op.drop_column('data_points', 'data_type')
    op.drop_column('data_points', 'task_id')
    # ### end Alembic commands ###
