#!/bin/bash
# Generate Aurora secret JSON for manual creation

echo "🔐 Aurora Secret Generator for wipsie-learning-aurora"
echo "===================================================="
echo ""

# Get Aurora endpoint (you may need to adjust this)
CLUSTER_ID="wipsie-learning-aurora"
PASSWORD="WipsieAurora2024!"

echo "📋 Secret details for wipsie-learning-aurora:"
echo ""
echo "Secret Name: wipsie-learning-aurora-credentials"
echo "Description: Aurora PostgreSQL credentials for wipsie learning cluster"
echo ""
echo "Secret Value (JSON):"
echo "{"
echo "  \"username\": \"postgres\","
echo "  \"password\": \"$PASSWORD\","
echo "  \"engine\": \"postgres\","
echo "  \"host\": \"$CLUSTER_ID.cluster-cq4e8fmhbjpd.us-east-1.rds.amazonaws.com\","
echo "  \"port\": 5432,"
echo "  \"dbname\": \"postgres\","
echo "  \"dbClusterIdentifier\": \"$CLUSTER_ID\""
echo "}"
echo ""
echo "🏷️  Tags to add:"
echo "Project: wipsie"
echo "Environment: learning"
echo "ManagedBy: manual"
echo ""
echo "💡 To create this secret manually:"
echo "1. Go to: https://console.aws.amazon.com/secretsmanager/newsecret?region=us-east-1"
echo "2. Choose 'Other type of secret'"
echo "3. Select 'Plaintext' tab"
echo "4. Paste the JSON above"
echo "5. Set secret name: wipsie-learning-aurora-credentials"
echo "6. Add the tags listed above"
echo "7. Click 'Store'"
